In [1]:
#Instalamos librería
#pip install git+https://github.com/griffisben/griffis_soccer_analysis.git

In [2]:
#Importamos librería
from griffis_soccer_analysis.similarity import *

In [3]:
#Listamos Ligas disponibles
available_leagues()

['1. HNL 23-24',
 '2. Bundesliga 23-24',
 '2. HNL 23-24',
 '3. Liga 23-24',
 'A-League Men 23-24',
 'Albanian Kategoria Superiore 23-24',
 'Allsvenskan 2023',
 'Andorra Primera Divisió 23-24',
 'Argentina Copa de la Liga 2024',
 'Argentina LPF 2023',
 'Argentina Primera Nacional 2023',
 'Argentina Primera Nacional 2024',
 'Argentina Reserve League 2023',
 'Armenian Premier League 23-24',
 'Austrian 2. Liga 23-24',
 'Austrian Bundesliga 23-24',
 'Azeri Birinci Dasta 23-24',
 'Azeri Premyer Liqa 23-24',
 'BRI Liga 1 23-24',
 'Bahrain Premier League 23-24',
 'Belgian First Division B 23-24',
 'Belgian Pro League 23-24',
 'Besta-deild karla 2023',
 'Bolivian LFPB 2023',
 'Bosnian Premier League 23-24',
 'Botola Pro 23-24',
 'Brasileirão 2023',
 'Brazil Serie B 2023',
 'Brazil Serie C 2023',
 'Bulgarian First League 23-24',
 'Bundesliga 23-24',
 'Cambodian Premier League 23-24',
 'Campeonato de Portugal 23-24',
 'Canadian Premier League 2023',
 'Capital Territory NPL 2023',
 'Championship 23-24',
 'Chilean Primera B 2023',
 'Chilean Primera División 2023',
 'China League One 2023',
 'China League Two 2023',
 'Chinese Super League 2023',
 'Colombian Primera A 2023',
 'Colombian Primera A 2024',
 'Colombian Torneo BetPlay 2023',
 'Colombian Torneo BetPlay 2024',
 'Costa Rican Primera División 23-24',
 'Cyprus 1. Division 23-24',
 'Cyprus 2. Division 23-24',
 'Czech FNL 23-24',
 'Czech Fortuna Liga 23-24',
 'Danish 1. Division 23-24',
 'Danish 2. Division 23-24',
 'Danish 3. Division 23-24',
 'Ecuador Liga Pro 2023',
 'Eerste Divisie 23-24',
 'Egyptian Premier League 23-24',
 'Ekstraklasa 23-24',
 'El Salvador Primera División 23-24',
 'Eliteserien 2023',
 'English National League 23-24',
 'English National League North South 23-24',
 'Eredivisie 23-24',
 'Erovnuli Liga 2 2023',
 'Erovnuli Liga 2023',
 'Estonia Meistriliiga 2023',
 'Estonian Esiliiga A 2023',
 'Ettan 2023',
 'French National 1 23-24',
 'Greek Super League 23-24',
 'Greek U19 Super League 23-24',
 'Guatemalan Liga Nacional 23-24',
 'Honduran Liga Nacional 23-24',
 'Hong Kong Premier League 23-24',
 'Iceland 1. Deild 2023',
 'Indian Super League 23-24',
 'Irish First Division 2023',
 'Irish Premier Division 2023',
 'J1 2023',
 'J2 2023',
 'J3 2023',
 'Jordan Pro League 23-24',
 'K League 1 2023',
 'K League 2 2023',
 'K3 League 2023',
 'K4 League 2023',
 'Kazakh 1. Division 2023',
 'Kazakh 2. Division 2023',
 'Kazakh Premier League 2023',
 'Kazakh U18 League 2023',
 'Kosovo Superliga 23-24',
 'Kyrgyz Premier League 2023',
 'La Liga 2 23-24',
 'La Liga 23-24',
 'Latvian 1. Liga 2023',
 'Latvian Virsliga 2023',
 'League One 23-24',
 'League Two 23-24',
 'Liga Leumit 23-24',
 'Liga MX 23-24',
 'Liga de Expansión MX 23-24',
 "Ligat ha'Al 23-24",
 'Ligue 1 23-24',
 'Ligue 2 23-24',
 'Lithuanian 1 Lyga 2023',
 'Lithuanian A Lyga 2023',
 'Luxembourg National Division 23-24',
 'MLS 2023',
 'MLS Next Pro 2023',
 'Malaysian Super League 2023',
 'Malta Challenge League 23-24',
 'Malta Premier League 23-24',
 'Moldovan Super Liga 23-24',
 'Motenegro First League 23-24',
 'Motenegro Second League 23-24',
 'NB I 23-24',
 'NB II 23-24',
 'New South Wales NPL 2023',
 'New Zealand National League 2023',
 'Nicaragua Primera Division 23-24',
 'North Macedonia First League 23-24',
 'Northern Irish Premiership 23-24',
 'Norwegian 2. Division 2023',
 'OBOS Ligaen 2023',
 'Panama LPF 2023',
 'Paraguay Division Profesional 2023',
 'Paraguay Division Profesional 2024',
 'Peruvian Liga 1 2023',
 'Peruvian Liga 1 2024',
 'Polish I Liga 23-24',
 'Polish II Liga 23-24',
 'Portuguese Liga 3 23-24',
 'Portuguese Segunda Liga 23-24',
 'Premier League 23-24',
 'Primeira Liga 23-24',
 'Primera RFEF 23-24',
 'Qatari Stars League 23-24',
 'Queensland NPL 2023',
 'Regionalliga 23-24',
 'Romanian Liga II 23-24',
 'Romanian Superliga 23-24',
 'Russian First League 23-24',
 'Russian Premier League 23-24',
 'Saudi Division 1 23-24',
 'Saudi Pro League 23-24',
 'Scottish Championship 23-24',
 'Scottish League One 23-24',
 'Scottish League Two 23-24',
 'Scottish Premiership 23-24',
 'Segunda RFEF 23-24',
 'Serbian Prva Liga 23-24',
 'Serbian Super Liga 23-24',
 'Serie A 23-24',
 'Serie B 23-24',
 'Serie C 23-24',
 'Singapore Premier League 2023',
 'Slovak 2. Liga 23-24',
 'Slovak Super Liga 23-24',
 'Slovenian 1. SNL 23-24',
 'Slovenian 2. SNL 23-24',
 'South Australia NPL 2023',
 'Superettan 2023',
 'Superliga 23-24',
 'Swiss 1. Liga Classic 23-24',
 'Swiss 1. Liga Promotion 23-24',
 'Swiss Challenge League 23-24',
 'Swiss Super League 23-24',
 'Süper Lig 23-24',
 'Thai League 1 23-24',
 'Thai League 2 23-24',
 'Tunisia Ligue 1 23-24',
 'Turkish 1. Lig 23-24',
 'Tweede Divisie 23-24',
 'U17 Bundesliga 23-24',
 'U19 Bundesliga 23-24',
 'UAE Pro League 23-24',
 'USL Championship 2023',
 'USL League 1 2023',
 'Ukrainian Persha Liga 23-24',
 'Ukrainian Premier League 23-24',
 'Uruguay Primera División 2023',
 'Uzbek Super League 2023',
 'V.League 1 23-24',
 'Veikkausliiga 2023',
 'Victoria NPL 2023',
 'Welsh Premier League 23-24',
 'Ykkönen 2023']

In [14]:
#Listamos los equipos disponibles de la liga que deseamos. El nombre de la liga debe coincidir exactamente con el del listado anterior.
teams_in_league(league='Premier League 23-24')

['Arsenal',
 'Aston Villa',
 'Bournemouth',
 'Brentford',
 'Brighton',
 'Burnley',
 'Chelsea',
 'Crystal Palace',
 'Everton',
 'Fulham',
 'Liverpool',
 'Luton Town',
 'Manchester City',
 'Manchester United',
 'Newcastle United',
 'Nottingham Forest',
 'Sheffield United',
 'Tottenham Hotspur',
 'West Ham United',
 'Wolverhampton Wanderers']

In [15]:
#Listamos los jugadores disponibles del equipo que deseamos. El nombre del equipo debe coincidir exactamente con el del listado anterior.
available_players(
    league = 'Premier League 23-24',
    team = 'Liverpool'
)

,Player_Team,Player,Age,Real Position
42960,"V. van Dijk (32, Liverpool, Premier League 23-24)",V. van Dijk,32,CB
43031,"L. Díaz (27, Liverpool, Premier League 23-24)",L. Díaz,27,Winger
43035,"Mohamed Salah (31, Liverpool, Premier League 23-24)",Mohamed Salah,31,Winger
43037,"A. Mac Allister (25, Liverpool, Premier League 23-24)",A. Mac Allister,25,DM
43051,"D. Szoboszlai (23, Liverpool, Premier League 23-24)",D. Szoboszlai,23,None
43057,"Alisson Becker (31, Liverpool, Premier League 23-24)",Alisson Becker,31,GK
43065,"D. Núñez (24, Liverpool, Premier League 23-24)",D. Núñez,24,ST
43093,"J. Gomez (26, Liverpool, Premier League 23-24)",J. Gomez,26,FB
43100,"T. Alexander-Arnold (25, Liverpool, Premier League 23-24)",T. Alexander-Arnold,25,FB
43127,"I. Konaté (24, Liverpool, Premier League 23-24)",I. Konaté,24,CB
43159,"W. Endo (31, Liverpool, Premier League 23-24)",W. Endo,31,DM
43166,"C. Gakpo (24, Liverpool, Premier League 23-24)",C. Gakpo,24,ST
43173,"A. Robertson (30, Liverpool, Premier League 23-24)",A. Robertson,30,FB
43212,"Diogo Jota (27, Liverpool, Premier League 23-24)",Diogo Jota,27,Winger
43219,"C. Jones (23, Liverpool, Premier League 23-24)",C. Jones,23,None
43224,"H. Elliott (21, Liverpool, Premier League 23-24)",H. Elliott,21,None
43231,"C. Kelleher (25, Liverpool, Premier League 23-24)",C. Kelleher,25,GK
43232,"R. Gravenberch (21, Liverpool, Premier League 23-24)",R. Gravenberch,21,None
43257,"J. Matip (32, Liverpool, Premier League 23-24)",J. Matip,32,CB
43273,"J. Quansah (21, Liverpool, Premier League 23-24)",J. Quansah,21,CB
43275,"K. Tsimikas (27, Liverpool, Premier League 23-24)",K. Tsimikas,27,FB
43286,"C. Bradley (20, Liverpool, Premier League 23-24)",C. Bradley,20,FB

In [16]:
#Ingresamos el nombre del jugador del cual obtendremos jugadores similares.
#Formato de la variable Player: "nombre_jugador(edad,Equipo,Liga)"
#Formato de la variable Position:"posición exacta del jugador"
df, info, base = player_similarity(
    player = "Mohamed Salah (31, Liverpool, Premier League 23-24)",
    position = "Winger",
    nplayers = 200,
    min_age = 20,   # Edad mínima de los jugadores similares (siempre dentro del 5% superior)
    max_age = 26,   # Edad máxima de los jugadores similares (siempre dentro del 5% superior)
    similar_lg_team = True,
    mean_sim = False,
)

In [17]:
#Hacemos un listado de 15 registros
df.head(15)

,Player,Player Style Similarity,League Style Similarity,Team Style Similarity
0,"O. Traore (21, Al Jazira, UAE Pro League 23-24)",87.34,57.47,80.29
1,"Abdulrahman Ghareeb (26, Al Nassr, Saudi Pro League 23-24)",86.94,55.39,85.46
2,"M. Milićković (25, Žalgiris, Lithuanian A Lyga 2023)",86.90,4.22,84.66
3,"M. Vargas (22, Colorado Rapids II, MLS Next Pro 2023)",86.87,77.85,56.93
4,"S. Moreno (23, Portland Timbers, MLS 2023)",86.69,76.11,6.26
5,"Min-Kyu Song (24, Jeonbuk Motors, K League 1 2023)",86.60,22.05,31.87
6,"J. Paesler (21, Gungahlin, Capital Territory NPL 2023)",86.12,18.54,76.81
7,"N. Milanovic (22, Western Sydney Wanderers, A-League Men 23-24)",85.58,84.38,86.86
8,"C. Tzolis (21, Fortuna Düsseldorf, 2. Bundesliga 23-24)",85.55,72.88,62.37
9,"A. Eminovic (24, United Nordic, Ettan 2023)",85.47,50.21,72.96
10,"J. Ceka (24, Magdeburg, 2. Bundesliga 23-24)",84.42,72.88,65.35
11,"Y. Asprilla (20, Watford, Championship 23-24)",84.38,70.46,63.51
12,"P. Kasim (26, Birmingham Legion, USL Championship 2023)",84.25,22.16,41.51
13,"Chang-gu Han (25, Yeoju Citizen, K4 League 2023)",84.09,39.91,74.30
14,"M. Larsen (23, Tromsdalen, Norwegian 2. Division 2023)",84.00,50.41,84.58

In [18]:
#Pasos para segmentar jugadores similares en ligas específicas. 
#En este caso, se realiza la segmentación dentro de las cinco grandes ligas.
ligas = ['Bundesliga 23-24',
 'Ligue 1 23-24',
 'La Liga 23-24',
 'Premier League 23-24',
 'Serie A 23-24']

In [19]:
# Extraer el nombre de la liga del campo Player
df['League'] = df['Player'].str.extract(r',\s*([^,]*\s*\d{2}-\d{2})\)')

In [20]:
# Mostrar los resultados de la extracción
print("Resultados de la extracción de ligas:")
print(df[['Player', 'League']])

Resultados de la extracción de ligas:
                                                                Player  \
0                      O. Traore (21, Al Jazira, UAE Pro League 23-24)
1           Abdulrahman Ghareeb (26, Al Nassr, Saudi Pro League 23-24)
2                 M. Milićković (25, Žalgiris, Lithuanian A Lyga 2023)
3                M. Vargas (22, Colorado Rapids II, MLS Next Pro 2023)
4                           S. Moreno (23, Portland Timbers, MLS 2023)
..                                                                 ...
123  J. Stewart (25, APIA Leichhardt Tigers, New South Wales NPL 2023)
124                            J. Bakayoko (20, PSV, Eredivisie 23-24)
125                    A. Muja (25, Antwerp, Belgian Pro League 23-24)
126                Batxi (25, Krasnodar, Russian Premier League 23-24)
127                 M. Suleiman (25, Spakenburg, Tweede Divisie 23-24)

                           League
0            UAE Pro League 23-24
1          Saudi Pro League 23-24
2                             NaN
3                             NaN
4                             NaN
..                            ...
123                           NaN
124              Eredivisie 23-24
125      Belgian Pro League 23-24
126  Russian Premier League 23-24
127          Tweede Divisie 23-24

[128 rows x 2 columns]

In [21]:
# Filtrar los jugadores que pertenecen a las ligas en la lista
df_filtered = df[df['League'].isin(ligas)]

In [22]:
# Mostrar los registros filtrados en un DataFrame
print("\nRegistros filtrados:")
print(df_filtered[['Player', 'League']].reset_index(drop=True))

Registros filtrados:
                                                        Player  \
0         Antony (23, Manchester United, Premier League 23-24)
1                     V. Tsygankov (26, Girona, La Liga 23-24)
2            L. Bailey (26, Aston Villa, Premier League 23-24)
3                    João Félix (24, Barcelona, La Liga 23-24)
4  D. Kulusevski (23, Tottenham Hotspur, Premier League 23-24)
5               Xavi Simons (20, RB Leipzig, Bundesliga 23-24)

                 League
0  Premier League 23-24
1         La Liga 23-24
2  Premier League 23-24
3         La Liga 23-24
4  Premier League 23-24
5      Bundesliga 23-24

In [23]:
#Obtenemos el resultado final con la lista de jugadores similares
df_filtered

,Player,Player Style Similarity,League Style Similarity,Team Style Similarity,League
21,"Antony (23, Manchester United, Premier League 23-24)",82.23,100.00,86.13,Premier League 23-24
40,"V. Tsygankov (26, Girona, La Liga 23-24)",80.27,74.92,74.56,La Liga 23-24
66,"L. Bailey (26, Aston Villa, Premier League 23-24)",78.37,100.00,78.05,Premier League 23-24
71,"João Félix (24, Barcelona, La Liga 23-24)",77.65,74.92,89.15,La Liga 23-24
113,"D. Kulusevski (23, Tottenham Hotspur, Premier League 23-24)",73.78,100.00,86.19,Premier League 23-24
117,"Xavi Simons (20, RB Leipzig, Bundesliga 23-24)",73.48,82.48,88.76,Bundesliga 23-24